export const GET_VIDEOS_LIST_REQUEST = 'GET_VIDEOS_LIST_REQUEST';
export const VIDEOS_LIST_FAILURE = 'VIDEOS_LIST_FAILURE';
export const VIDEOS_LIST_SUCCESS = 'VIDEOS_LIST_SUCCESS';

export const SINGLE_VIDEO_REQUEST = 'SINGLE_VIDEO_REQUEST';
export const SINGLE_VIDEO_SUCCESS = 'SINGLE_VIDEO_SUCCESS';
export const SINGLE_VIDEO_FAILURE = 'SINGLE_VIDEO_FAILURE';

export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';

export const ADD_WATCH_LATER = 'ADD_WATCH_LATER';
export const REMOVE_WATCH_LATER = 'REMOVE_WATCH_LATER';
export const CLEAR_WATCH_LATER = 'CLEAR_WATCH_LATER';

export const LIKE_VIDEO = 'LIKE_VIDEO';
export const REMOVE_LIKE_VIDEO = 'REMOVE_LIKE_VIDEO';

export const SEARCH_KEYWORD = 'SEARCH_KEYWORD';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const ADD_NEW_PLAYLIST = 'ADD_NEW_PLAYLIST';
export const ADD_ITEM_TO_PLAYLIST = 'ADD_ITEM_TO_PLAYLIST';
export const REMOVE_ITEM_FROM_PLAYLIST = 'REMOVE_ITEM_FROM_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
