export const GET_VIDEOS_LIST_REQUEST = 'GET_VIDEOS_LIST_REQUEST';
export const VIDEOS_LIST_FAILURE = 'VIDEOS_LIST_FAILURE';
export const VIDEOS_LIST_SUCCESS = 'VIDEOS_LIST_SUCCESS';
export const SINGLE_VIDEO_REQUEST = 'SINGLE_VIDEO_REQUEST';
export const SINGLE_VIDEO_SUCCESS = 'SINGLE_VIDEO_SUCCESS';
export const SINGLE_VIDEO_FAILURE = 'SINGLE_VIDEO_FAILURE';
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';